import type { GlobalConfig, Field } from 'payload'
import { editor, published } from '@/lib/access'
import { image, gallery, body, pageOptions, safeURL } from '@/lib/fields'
const access = { read: published, update: editor, readVersions: editor }
const versions = { drafts: true, maxPerDoc: 50 }
const common = { access, versions, admin: { group: 'Страницы и настройки' } }
export const Home: GlobalConfig = {
  slug: 'home', label: 'Главная', ...common,
  admin: { ...common.admin, preview: () => '/preview?path=/' },
  fields: [image, { name: 'heading', label: 'Заголовок первого экрана', type: 'text', required: true, defaultValue: 'Предметы с характером' }, { name: 'subtitle', label: 'Подпись', type: 'textarea' },
    { name: 'primaryLabel', label: 'Текст кнопки каталога', type: 'text', defaultValue: 'Смотреть коллекцию', required: true }, { name: 'secondaryLabel', label: 'Текст кнопки обращения', type: 'text', defaultValue: 'Обсудить заказ', required: true },
    { name: 'featured', label: 'Избранные предметы', type: 'relationship', relationTo: 'items', hasMany: true },
    { name: 'story', label: 'История мастерской', type: 'textarea' }, { name: 'customOrder', label: 'Индивидуальный заказ', type: 'textarea' },
    { name: 'sections', label: 'Порядок и видимость секций', type: 'array', fields: [{ name: 'section', label: 'Секция', type: 'select', required: true, options: [{ label: 'Избранные', value: 'featured' }, { label: 'Категории', value: 'categories' }, { label: 'Мастерская', value: 'workshop' }, { label: 'Индивидуальный заказ', value: 'custom' }, { label: 'Шоурумы', value: 'showrooms' }] }, { name: 'visible', label: 'Показывать', type: 'checkbox', defaultValue: true }], defaultValue: ['featured', 'categories', 'workshop', 'custom', 'showrooms'].map(section => ({ section, visible: true })) }],
}
export const Workshop: GlobalConfig = { slug: 'workshop', label: 'Мастерская', ...common, admin: { ...common.admin, preview: () => '/preview?path=/workshop' }, fields: [{ name: 'heading', label: 'Заголовок', type: 'text', defaultValue: 'Мастерская KILTA' }, body, image, gallery, { name: 'customOrder', label: 'Индивидуальный заказ', type: 'textarea' }] }
export const Appearance: GlobalConfig = { slug: 'appearance', label: 'Оформление', ...common, fields: [{ name: 'theme', label: 'Тема', type: 'select', required: true, defaultValue: 'gallery', options: [{ label: 'Светлая галерея', value: 'gallery' }, { label: 'Тёплая мастерская', value: 'warm' }, { label: 'Тёмный арт-каталог', value: 'dark' }] }, { name: 'accent', label: 'Акцент', type: 'select', defaultValue: 'natural', options: [{ label: 'Нейтральный', value: 'natural' }, { label: 'Терракота', value: 'clay' }, { label: 'Оливковый', value: 'olive' }], admin: { description: 'Палитры подобраны для читаемости во всех трёх темах. Произвольный CSS не поддерживается.' } }, { name: 'logo', label: 'Логотип', type: 'upload', relationTo: 'media' }, { name: 'favicon', label: 'Иконка сайта', type: 'upload', relationTo: 'media' }] }
export const Contacts: GlobalConfig = { slug: 'contacts', label: 'Контакты и реквизиты', ...common, fields: [{ name: 'phone', label: 'Телефон', type: 'text' }, { name: 'email', label: 'Email', type: 'email' }, { name: 'address', label: 'Адрес', type: 'textarea' }, { name: 'seller', label: 'Реквизиты продавца', type: 'textarea' }, { name: 'social', label: 'Социальные сети', type: 'array', fields: [{ name: 'label', label: 'Название', type: 'text', required: true }, { name: 'url', label: 'Ссылка', type: 'text', required: true, validate: safeURL }] }] }
const navFields: Field[] = [{ name: 'label', label: 'Название пункта', type: 'text', required: true }, { name: 'href', label: 'Страница', type: 'select', required: true, options: pageOptions }]
export const Navigation: GlobalConfig = { slug: 'navigation', label: 'Навигация и подвал', ...common, fields: [{ name: 'links', label: 'Меню', type: 'array', fields: navFields, defaultValue: pageOptions.slice(1).map(p => ({ label: p.label, href: p.value })) }, { name: 'footerText', label: 'Подпись в подвале', type: 'textarea', defaultValue: 'Авторская мебель и скульптуры' }, { name: 'documents', label: 'Документы в подвале', type: 'relationship', relationTo: 'documents', hasMany: true }] }
export const SEO: GlobalConfig = { slug: 'seo', label: 'SEO', ...common, fields: [{ name: 'siteName', label: 'Название сайта', type: 'text', required: true, defaultValue: 'KILTA' }, { name: 'description', label: 'Описание по умолчанию', type: 'textarea', defaultValue: 'Авторская мебель и скульптуры KILTA' }, { name: 'ogImage', label: 'Изображение для социальных сетей', type: 'upload', relationTo: 'media' }] }
