/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pdfs: Pdf;
    categories: Category;
    items: Item;
    showrooms: Showroom;
    documents: Document;
    'document-revisions': DocumentRevision;
    inquiries: Inquiry;
    'rate-limits': RateLimit;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pdfs: PdfsSelect<false> | PdfsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    showrooms: ShowroomsSelect<false> | ShowroomsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'document-revisions': DocumentRevisionsSelect<false> | DocumentRevisionsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'rate-limits': RateLimitsSelect<false> | RateLimitsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    workshop: Workshop;
    appearance: Appearance;
    contacts: Contact;
    navigation: Navigation;
    seo: Seo;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    workshop: WorkshopSelect<false> | WorkshopSelect<true>;
    appearance: AppearanceSelect<false> | AppearanceSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Роли назначает только разработчик.
   */
  role: 'owner' | 'developer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * JPEG, PNG, WebP, AVIF, до 20 МБ. Неиспользуемые и черновые файлы доступны только редакторам.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdfs".
 */
export interface Pdf {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Латинские буквы, цифры и дефисы. Например: derevyannaya-skulptura.
   */
  slug: string;
  image?: (number | null) | Media;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  title: string;
  /**
   * Латинские буквы, цифры и дефисы. Например: derevyannaya-skulptura.
   */
  slug: string;
  categories?: (number | Category)[] | null;
  image?: (number | null) | Media;
  /**
   * Добавьте фотографии и перетаскивайте строки, чтобы менять порядок.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  materials?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  dimensions?: {
    height?: number | null;
    width?: number | null;
    depth?: number | null;
  };
  unit: 'cm' | 'mm';
  priceMode: 'request' | 'exact' | 'from';
  price?: number | null;
  currency: 'RUB';
  availability: 'order' | 'stock' | 'sold';
  leadTime?: string | null;
  options?: string | null;
  featured?: boolean | null;
  demo?: boolean | null;
  order?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showrooms".
 */
export interface Showroom {
  id: number;
  title: string;
  /**
   * Латинские буквы, цифры и дефисы. Например: derevyannaya-skulptura.
   */
  slug: string;
  city: string;
  address: string;
  hours?: string | null;
  contacts?: string | null;
  /**
   * Добавьте фотографии и перетаскивайте строки, чтобы менять порядок.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Проверьте ссылку перед публикацией. Карта открывается только по нажатию.
   */
  routeURL?: string | null;
  items?: (number | Item)[] | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  /**
   * Латинские буквы, цифры и дефисы. Например: derevyannaya-skulptura.
   */
  slug: string;
  type: 'privacy' | 'consent' | 'offer' | 'delivery' | 'returns' | 'details' | 'cookies';
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  editionDate: string;
  effectiveDate?: string | null;
  pdf?: (number | null) | Pdf;
  showInFooter?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-revisions".
 */
export interface DocumentRevision {
  id: number;
  document: number | Document;
  title: string;
  /**
   * Латинские буквы, цифры и дефисы. Например: derevyannaya-skulptura.
   */
  slug: string;
  type?: ('privacy' | 'consent' | 'offer' | 'delivery' | 'returns' | 'details' | 'cookies') | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pdf?: (number | null) | Pdf;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  item?: (number | null) | Item;
  name: string;
  contact: string;
  channel: 'email' | 'phone';
  message?: string | null;
  consent: boolean;
  consentRevision: number | DocumentRevision;
  privacyRevision: number | DocumentRevision;
  status?: ('new' | 'progress' | 'done') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits".
 */
export interface RateLimit {
  id: number;
  key: string;
  count: number;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pdfs';
        value: number | Pdf;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'showrooms';
        value: number | Showroom;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'document-revisions';
        value: number | DocumentRevision;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'rate-limits';
        value: number | RateLimit;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdfs_select".
 */
export interface PdfsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  categories?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  materials?:
    | T
    | {
        name?: T;
        id?: T;
      };
  dimensions?:
    | T
    | {
        height?: T;
        width?: T;
        depth?: T;
      };
  unit?: T;
  priceMode?: T;
  price?: T;
  currency?: T;
  availability?: T;
  leadTime?: T;
  options?: T;
  featured?: T;
  demo?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showrooms_select".
 */
export interface ShowroomsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  city?: T;
  address?: T;
  hours?: T;
  contacts?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  routeURL?: T;
  items?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  body?: T;
  editionDate?: T;
  effectiveDate?: T;
  pdf?: T;
  showInFooter?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-revisions_select".
 */
export interface DocumentRevisionsSelect<T extends boolean = true> {
  document?: T;
  title?: T;
  slug?: T;
  type?: T;
  body?: T;
  pdf?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  item?: T;
  name?: T;
  contact?: T;
  channel?: T;
  message?: T;
  consent?: T;
  consentRevision?: T;
  privacyRevision?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits_select".
 */
export interface RateLimitsSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  image?: (number | null) | Media;
  heading: string;
  subtitle?: string | null;
  primaryLabel: string;
  secondaryLabel: string;
  featured?: (number | Item)[] | null;
  story?: string | null;
  customOrder?: string | null;
  sections?:
    | {
        section: 'featured' | 'categories' | 'workshop' | 'custom' | 'showrooms';
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop".
 */
export interface Workshop {
  id: number;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Добавьте фотографии и перетаскивайте строки, чтобы менять порядок.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  customOrder?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance".
 */
export interface Appearance {
  id: number;
  theme: 'gallery' | 'warm' | 'dark';
  /**
   * Палитры подобраны для читаемости во всех трёх темах. Произвольный CSS не поддерживается.
   */
  accent?: ('natural' | 'clay' | 'olive') | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  seller?: string | null;
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  links?:
    | {
        label: string;
        href: '/' | '/catalog' | '/workshop' | '/showrooms' | '/contacts';
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  documents?: (number | Document)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  siteName: string;
  description?: string | null;
  ogImage?: (number | null) | Media;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  subtitle?: T;
  primaryLabel?: T;
  secondaryLabel?: T;
  featured?: T;
  story?: T;
  customOrder?: T;
  sections?:
    | T
    | {
        section?: T;
        visible?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop_select".
 */
export interface WorkshopSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  customOrder?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance_select".
 */
export interface AppearanceSelect<T extends boolean = true> {
  theme?: T;
  accent?: T;
  logo?: T;
  favicon?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  seller?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerText?: T;
  documents?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  siteName?: T;
  description?: T;
  ogImage?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}